# Generated by Django 4.2.1 on 2023-05-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_enrollment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='UserEnrollment',
        ),
    ]
