# Generated by Django 4.2.1 on 2023-05-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_enrollment_userenrollment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEnrollment',
            new_name='StudentEnrollment',
        ),
    ]
